import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'

import { getAllMembers } from './authService'
import { RootState } from '../../app/store'

export interface authStateInterface {
  value: []
  error: any
  status: 'idle' | 'loading' | 'failed'
}

const initialState: authStateInterface = {
  value: [],
  error: '',
  status: 'idle',
}

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getMembers = createAsyncThunk(
  'auth/getAllMembers',
  async (_, { rejectWithValue }) => {
    try {
      return await await getAllMembers()
    } catch (error: any) {
      return rejectWithValue(error.message)
    }
  }
)

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    test: (state) => {
      // Redux Toolkit allows us to write "mutating" logic in reducers. It
      // doesn't actually mutate the state because it uses the Immer library,
      // which detects changes to a "draft state" and produces a brand new
      // immutable state based off those changes
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getMembers.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(getMembers.fulfilled, (state, action) => {
        state.status = 'idle'
        state.value = action.payload
      })
      .addCase(getMembers.rejected, (state, action) => {
        state.status = 'failed'
        state.error = action.payload
      })
  },
})

export const { test } = authSlice.actions

export const allMembers = (state: RootState) => state.auth

export default authSlice.reducer
